---
title: "inspect_observed_dataset"
author: "QingXuan Kong"
date: "2020/9/19"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(glue)
```

## us timeseries

```{r}
raw_timeseries <-
  read_csv("US_20200919_timeseries.csv", col_types = "cDcccciiiiiiiiiiiiii")
mydata <- raw_timeseries %>%
  filter(aggregate_level == "state") %>%
  select(fips,
         state,
         date,
         cases,
         deaths,
         cumulative_hospitalized,
         current_hospitalized) %>%
  group_by(state) %>% 
  mutate(
    I1_increase = cases - lag(cases, n = 1),
    hosp_increase = cumulative_hospitalized - lag(cumulative_hospitalized, n = 1),
    D_increase = deaths - lag(deaths, n = 1)
  )

# mydata %>%
#   group_by(state) %>%
#   mutate(hospitalized_increase = cumulative_hospitalized - lag(cumulative_hospitalized, n = 1)) %>%
#   summarise(
#     cumu_na_rate = mean(is.na(cumulative_hospitalized)),
#     curr_na_rate = mean(is.na(current_hospitalized)),
#     cumu_lessna = (cumu_na_rate < curr_na_rate),
#     cumu_decrease = sum(hospitalized_increase < 0, na.rm = TRUE),
#     prefer_cumu = cumu_lessna & (!cumu_decrease)
#   ) %>%
#   View()

## check NAs

# first_nonNA_date <- function(vec, r = FALSE)
# {
#   if (r == FALSE)
#   {
#     index <- match(x = 1, table = !is.na(vec))
#   }
#   else if (r == TRUE)
#   {
#     index <- match(x = 1, table = !is.na(rev(vec)))
#     index <- length(vec) - index + 1
#   }
#   return(mydata$date[index])
# }

# mydata %>%
#   group_by(state) %>%
#   summarise(
#     I1_first = first_nonNA_date(cases, r = F),
#     I1_last = first_nonNA_date(cases, r = T),
#     I1_nonna_count = sum(!is.na(cases)),
#     hosp_cur_first = first_nonNA_date(current_hospitalized, r = F),
#     hosp_cur_last = first_nonNA_date(current_hospitalized, r = T),
#     hosp_cur_nonna_count = sum(!is.na(current_hospitalized)),
#     hosp_cumu_first = first_nonNA_date(cumulative_hospitalized, r = F),
#     hosp_cumu_last = first_nonNA_date(cumulative_hospitalized, r = T),
#     hosp_cumu_nonna_count = sum(!is.na(cumulative_hospitalized)),
#     D_first = first_nonNA_date(deaths, r = F),
#     D_last = first_nonNA_date(deaths, r = T),
#     D_nonna_count = sum(!is.na(deaths))
#   ) %>% 
#   View()

# func_list <- list(
#   first =  ~ first_nonNA_date(.x, r = F),
#   last =  ~ first_nonNA_date(.x, r = T),
#   count =  ~ sum(!is.na(.x))
# )

## check NAs
mydata %>% 
  group_by(state) %>% 
  rename(I1=cases,hosp_cur=current_hospitalized,hosp_cumu=cumulative_hospitalized,D=deaths) %>% 
  summarise(across(c(I1,hosp_cur,hosp_cumu,D),    c(
      first =  ~ date[match(x = 1, table = !is.na(.x))],
      last =  ~ date[(length(.x) - match(x = 1, table = !is.na(rev(.x))) + 1)],
      count =  ~ sum(!is.na(.x))
    ),.name="{.fn}_{.col}")) %>% 
  View()


## plot 
for(state_ac in unique(mydata$state))
{
  temp_mydata <- mydata %>% filter(state==state_ac)
  for (i in 1:4)
  {
    v_name <- c("I1_increase", "hosp_cur", "hosp_increase", "D_increase")[i]
    c_name <-
      c("I1_increase",
        "current_hospitalized",
        "hosp_increase",
        "D_increase")[i]
    
    if (!file.exists(paste0("inspection_outputs/USA/",v_name)))
        dir.create(paste0("inspection_outputs/USA/",v_name))
    
    temp_plot <- ggplot(temp_mydata) +
      geom_point(aes(x=date,y=temp_mydata[[c_name]])) +
      labs(x="Date",y=c_name,title = paste0(state_ac,"_",v_name))
    
    ggsave(filename = paste0(state_ac,"_",v_name,".png"),
           plot = temp_plot,
           path = paste0("inspection_outputs/USA/",v_name,"/"))
    
  }
}
```

## the canada timeseries
```{r}
raw_timeseries <- read_csv("CA_20200919_Provincial_Daily_Totals.csv",col_types = "icciciiiiiiiiiiiii")

mydata <- raw_timeseries %>% 
  mutate(Date=parse_date(str_sub(SummaryDate,end = 10))) %>% 
  select(Abbreviation,Date,starts_with("Daily"))

## check Nas
mydata %>%
  group_by(Abbreviation) %>%
  summarise(across(
    starts_with("Daily"),
    c(
      first =  ~ Date[match(x = 1, table = !is.na(.x))],
      last =  ~ Date[(length(.x) - match(x = 1, table = !is.na(rev(.x))) + 1)],
      na_count =  ~ sum(!is.na(.x)),
      zero_count = ~ sum(!.x==0,na.rm = T),
      data_perc = ~ sum(!.x==0,na.rm = T)/sum(!is.na(.x))
    ),
    .names = "{.fn}_{.col}"
  )) %>%
  #select(Abbreviation,starts_with("data")) %>% 
  View()

## plot
for (state_ac in unique(mydata$Abbreviation))
{
  temp_mydata <- mydata %>% filter(Abbreviation == state_ac)
  for (i in 1:4)
  {
    v_name <- c("I1", "I2", "I3", "D")[i]
    c_name <-
      c("DailyTotals",
        "DailyHospitalized",
        "DailyICU",
        "DailyDeaths")[i]
    
    if (!file.exists(paste0("inspection_outputs/Canada/", v_name)))
      dir.create(paste0("inspection_outputs/Canada/", v_name))
    
    temp_plot <- ggplot(temp_mydata) +
      geom_point(aes(x = Date, y = temp_mydata[[c_name]])) +
      labs(x = "Date",
           y = v_name,
           title = paste0(state_ac, "_", v_name))
    
    ggsave(
      filename = paste0(state_ac, "_", v_name, ".png"),
      plot = temp_plot,
      path = paste0("inspection_outputs/Canada/", v_name, "/")
    )
  }
  
}

```

