---
title: "1p3m_inspection"
author: "QingXuan Kong"
date: "2020/11/24"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## library
```{r}
library(tidyverse)
library(patchwork)
```

## import
```{r}
raw_data_1p3m <- read_csv("cases.csv")
raw_data_can <- read_csv("../US_timeseries.csv", col_types = "cDcccciiiiiiiiiiiiii")


reference_date <- parse_date("2020-01-01")
mydata_can <- raw_data_can %>%
  filter(aggregate_level == "state") %>% 
  group_by(state) %>% 
  mutate(cases_increase = cases - lag(cases, n = 1)) %>%
  mutate(deaths_increase = deaths - lag(deaths, n = 1))

mydata_1m3p <- raw_data_1p3m %>% 
  group_by(confirmed_date,state_name) %>% 
  summarise(case_increase=sum(confirmed_count),death_increase=sum(death_count))

```

## inspection
```{r}
raw_data_1p3m %>% 
  filter(state_name=="IL",county_name=="Cook") %>% 
  ggplot() +
  geom_line(aes(x=confirmed_date,y=confirmed_count))


mydata_can %>% 
  filter(state="IL")
  ggplot() +
  geom_line(aes(x=date,y=cases_increase))

  
  
mean(raw_data_1p3m$recovered_count<0)

## where are these negatives?
raw_data_1p3m %>% 
  select(-case_id,-FIPS,-recovered_count) %>% 
  group_by(state_name,county_name) %>% 
  summarise(nega_case=sum(confirmed_count<0),nega_death=sum(death_count<0)) %>% 
  filter(nega_case!=0,nega_death!=0) %>% 
  View()
# they are correction, I guess?

## 1p3m vs can
plot_1m3p <- mydata_1m3p %>% 
  filter(state_name=="IL") %>% 
  ggplot() +
  geom_line(aes(x=confirmed_date,y=case_increase)) +
  coord_cartesian(ylim = c(0, 15000))

plot_can <- mydata_can %>% 
  filter(state=="IL") %>% 
  ggplot() +
  geom_line(aes(x=date,y=cases_increase)) +
  coord_cartesian(ylim = c(0, 15000))

plot_1m3p+plot_can
# identical?
temp_1m3p <-  mydata_1m3p %>% 
  filter(state_name=="IL") %>% 
  filter(confirmed_date>parse_date("2020-04-01"),confirmed_date<parse_date("2020-09-01")) %>% 
  .$case_increase

temp_can <- mydata_can %>% 
  filter(state=="IL") %>% 
  filter(date>parse_date("2020-04-01"),date<parse_date("2020-09-01")) %>% 
  .$cases_increase

identical(temp_1m3p,temp_can) #F
(temp_1m3p-temp_can) %>% View() # diff up to 200
``` 

## transform
```{r}
mydata_1p3m <- raw_data_1p3m %>% 
  select(confi)
```

## plot all
```{r}
raw_data_1m3f <- read_csv("US_timeseries.csv")

mydata_1m3f <- raw_data_1m3f %>% 
  group_by(confirmed_date,state_name) %>% 
  summarise(cases_increase=sum(confirmed_count),deaths_increase=sum(death_count))

for (s_name in unique(mydata_1m3f$state_name)) {
  temp_plot <- mydata_1m3f %>%
    filter(state_name == s_name) %>%
    ggplot() + geom_point(aes(x = confirmed_date, y = cases_increase))
  
  ggsave(glue("{s_name}_cases.png"),
         plot = temp_plot,
         path = "outputs/cases/")
  
  temp_plot <- mydata_1m3f %>%
    filter(state_name == s_name) %>%
    ggplot() + geom_point(aes(x = confirmed_date, y = deaths_increase))
  
  ggsave(glue("{s_name}_deaths.png"),
         plot = temp_plot,
         path = "outputs/deaths/")
}

```

## what's these negative?
```{r}
raw_data_1m3f %>% 
  select(-case_id,-FIPS,-recovered_count) %>% 
  group_by(state_name,county_name) %>% 
  summarise(nega_case=sum(confirmed_count<0),nega_death=sum(death_count<0)) %>% 
  filter(nega_case!=0|nega_death!=0) %>% 
  View()

raw_data_1m3f %>% 
  mutate(ce1=lag(confirmed_count,1),ce2=lag(confirmed_count,2),cl1=lead(confirmed_count,1),cl2=lead(confirmed_count,2)) %>% 
  filter(confirmed_count< -100|death_count< -100) %>% 
  View()

raw_data_1m3f %>% 
  filter(state_name=="LA") %>% 
  View()
```


